import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@/components/ThemeProvider';
import { Navbar } from '@/components/Navbar';
import {css} from '../styled-system/css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Micelio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="es" suppressHydrationWarning className={css({ h: 'full' })}>
      <body className={css({ 
        bg: 'background', // Esto asegura que el fondo "sobrante" sea del tema
        color: 'text',
        minH: 'full', 
        display: 'flex',
        flexDirection: 'column'
      })}>
        <ThemeProvider>
          <Navbar />
          {/* El div envoltorio asegura que el contenido empuje hacia abajo */}
          <div className={css({ flex: '1' })}>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
